Add option to ignore failures for `pip install` when using `installRequirements`
airflow-helm/charts pull request #22
Opened 2020-11-24 16:09 UTC by chris-vest

**What issues does your PR fix?**

Nothing, adds a feature. In our environment we had some issues where Airflow would go into a crashLoopBackoff when there was an issue installing requirements.txt - this will allow for Airflow to start in such a scenario.

**What does your PR do?**

Adds option to ignore failures from the `install-requirements.sh` script, particularly the `pip install` command.

## Checklist

- [x] Commits are [signed](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#sign-your-work)
- [x] Commits are [squashed](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#squash-commits) (if appropriate)
- [x] Chart [version bumped](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#versioning)
- [x] Chart [documentation updated](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#documentation)
- [] Passes [linting](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#linting)

2020-11-24 16:19 UTC, gsemet approved these changes
look good to me. @thesuperzapper do you approve as well?

2020-11-24 22:45 UTC, thesuperzapper commented
@chris-vest some questions:

1. I am a little confused why someone would want to do this  (rather than just disabling `dags.installRequirements`)
2. I don't think `dags.ignoreFailures` is a good variable name (perhaps `dags.installRequirementsIgnoreFailures`)
3. I am going to rewrite how we do `pip install`, so I am not sure its worth a release to change the behaviour of the old system. (See: https://github.com/airflow-helm/charts/issues/3)

2020-11-24 22:46 UTC, thesuperzapper requested changes
see above

2020-11-25 06:18 UTC, chris-vest commented
> @chris-vest some questions:
> 
>     1. I am a little confused why someone would want to do this  (rather than just disabling `dags.installRequirements`)
> 
>     2. I don't think `dags.ignoreFailures` is a good variable name (perhaps `dags.installRequirementsIgnoreFailures`)
> 
>     3. I am going to rewrite how we do `pip install`, so I am not sure its worth a release to change the behaviour of the old system. (See: #3)

1) The reason I wanted to do this was because the data team at my company updated their requirements.txt and included a package which they hadn't published yet, this causes the `pip install` to fail and Airflow would never start. This caused a lot of noise in the alert system, especially because they didn't have time / didn't want to fix it in a timely manner. This PR would have allowed us to ignore the failed `pip install` and not have any alerts.

2) Agreed!

3) Your proposal looks better than what I've done.

2020-11-25 08:32 UTC, gsemet commented
do you know you can install from source code from the requirements.txt as well ?

2020-11-25 08:39 UTC, chris-vest commented
> do you know you can install from source code from the requirements.txt as well ?

As in from the Git sync?

2020-11-25 08:52 UTC, gsemet commented
No, I mean if you want to pip install a package that is not on pypi but on your local/internal git repository, you can use a line
```
git+https://myinternalserver/path/to/my/internal/package.git
```

2020-11-25 09:03 UTC, chris-vest commented
I didn't know that! Thanks for the tip.

2020-11-25 09:04 UTC, closed without merging