Add validation that `AIRFLOW__WEBSERVER__SECRET_KEY` is set when web is replicated
airflow-helm/charts pull request #315
Opened 2021-07-18 03:13 UTC by henryzhangsta

Signed-off-by: Henry Zhang <me@henry.dev>

**What issues does your PR fix?**

- fixes #265 

**What does your PR do?**

Adds validation that `AIRFLOW__WEBSERVER__SECRET_KEY` is set when web replicas is more than one.

## Checklist

- [x] Commits are [signed](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#sign-your-work)
- [x] Commits are [squashed](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#squash-commits) (only do this if appropriate)
- [ ] Chart [version bumped](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#versioning) (only do this if releasing a new version)
- [x] Chart [documentation updated](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#documentation)
- [x] Passes [linting](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#linting)

2021-07-21 09:35 UTC, thesuperzapper requested changes
@henryzhangsta I love this approach!

I never thought of using a temporary `$foundKey` variable to loop through the `extraEnv`!

2021-07-21 09:35 UTC, thesuperzapper commented on charts/airflow/templates/_helpers/validate-values.tpl
> +      {{ required "AIRFLOW__WEBSERVER__SECRET_KEY is required to be set when there is more than one web replica" nil }}
Can you change the error message to be more consistent with the rest, for example:
```
If `web.replicas > 1`, you must define `AIRFLOW__WEBSERVER__SECRET_KEY`!
```

2021-07-21 09:35 UTC, thesuperzapper commented on charts/airflow/values.yaml
> +  ## - if this is greater than one, then `AIRFLOW__WEBSERVER__SECRET_KEY` is required to be configured
To make it consistent with the line above, can you make the string:
```
  ## the number of web Pods to run
  ##
  ## WARNING:
  ##  - if set greater than `1`, you MUST set `AIRFLOW__WEBSERVER__SECRET_KEY`,
  ##    this prevents "CSRF session token is missing" errors when users are served by multiple web pods
  ##
  ## NOTE:
  ## - if set greater than `1`, we recommend defining a `web.podDisruptionBudget`
  ##
```

2021-07-22 21:41 UTC, henryzhangsta commented
@thesuperzapper updated

2021-08-09 04:12 UTC, thesuperzapper commented
@henryzhangsta sorry to do this, but this PR is no longer needed, this is because as of airflow `2.1.2`, EVERY INSTALL needs to set `AIRFLOW__WEBSERVER__SECRET_KEY` (see issue https://github.com/airflow-helm/charts/issues/327). Therefore, I have made PR https://github.com/airflow-helm/charts/pull/346, which adds `airflow.webserverSecretKey` to ensure that `AIRFLOW__WEBSERVER__SECRET_KEY` is always set.

However, I plan to implement your extremely clever method to check the various places which `AIRFLOW__WEBSERVER__SECRET_KEY` in solving https://github.com/airflow-helm/charts/issues/333 (warning the user to set a non-default value).

Please don't let this discourage you from contributing to the chart, you have been awsome!

2021-08-09 04:12 UTC, closed without merging