feat: add `ingressClassName` value to ingress
airflow-helm/charts pull request #527
Opened 2022-02-22 14:53 UTC by fkoetzner

## What issues does your PR fix?

- resolves #427
- fixes #425 
- replaces #426
- replaces #524

## What does your PR do?

- Adds the following values to allow setting `ingressClassName` on the Ingress resources:
   - `ingress.web.ingressClassName`
   - `ingress.flower.ingressClassName`

## Checklist

### For all Pull Requests

- [x] Commits are [signed off](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#sign-your-work)
- [x] Commits have [semantic messages](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#semantic-commit-messages)
- [x] Documentation [updated](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#documentation)
- [x] Passes [ct linting](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#linting)

### For releasing ONLY

- [ ] Chart.yaml [version bumped](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#versioning)
- [ ] CHANGELOG.md updated

---

_P.S.: Sorry, I accidentally closed the original pull request #524_.

2022-02-23 05:33 UTC, thesuperzapper requested changes
@fkoetzner this looks good now, with only one random diff to be fixed.

Also, you can re-open closed PRs, you don't have to make new ones, otherwise, it's sort of spammy.

2022-02-23 05:33 UTC, thesuperzapper commented on charts/airflow/README.md
> +</details>
Please remove this random diff.

2022-02-23 11:03 UTC, thesuperzapper approved these changes

2022-02-23 11:12 UTC, thesuperzapper commented
@fkoetzner I just realised that we haven't added `ingressClassName` to the `v1beta1` versions of the Ingresses:
- [./templates/webserver/webserver-ingress-v1beta1.yaml](https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/webserver/webserver-ingress-v1beta1.yaml)
- [./templates/flower/flower-ingress-v1beta1.yaml](https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/flower/flower-ingress-v1beta1.yaml)

Can you clarify if `v1beta1` ingresses have the `ingressClassName` field (as of Kubernetes 1.18+)?
- If YES, then we need to also include the value in those files
- If NO, then we should  add a new validation to [_helpers/validate-values.tpl](https://github.com/airflow-helm/charts/blob/df99a33e3278de9f6935e747e8317794966ed979/charts/airflow/templates/_helpers/validate-values.tpl#L94-L95) that fails if `ingress.apiVersion` is `networking.k8s.io/v1beta1` AND either `ingressClassName` is non-empty.

2022-02-23 13:17 UTC, fkoetzner commented
> @fkoetzner I just realised that we haven't added `ingressClassName` to the `v1beta1` versions of the Ingresses:
> 
>     * [./templates/webserver/webserver-ingress-v1beta1.yaml](https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/webserver/webserver-ingress-v1beta1.yaml)
> 
>     * [./templates/flower/flower-ingress-v1beta1.yaml](https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/flower/flower-ingress-v1beta1.yaml)
> 
> 
> Can you clarify if `v1beta1` ingresses have the `ingressClassName` field (as of Kubernetes 1.18+)?
> 
>     * If YES, then we need to also include the value in those files
> 
>     * If NO, then we should  add a new validation to [_helpers/validate-values.tpl](https://github.com/airflow-helm/charts/blob/df99a33e3278de9f6935e747e8317794966ed979/charts/airflow/templates/_helpers/validate-values.tpl#L94-L95) that fails if `ingress.apiVersion` is `networking.k8s.io/v1beta1` AND either `ingressClassName` is non-empty.

Yes, you're right. I thought it was only added to `networking.k8s.io/v1`, but I tested it with `v1beta1` and it works. Also, [this](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/) confirms that `v1beta1` has this field.

2022-03-22 00:46 UTC, thesuperzapper approved these changes

2022-04-01 07:51 UTC, merged