feat: add `dags.gitSync.submodules` value
airflow-helm/charts pull request #620
Opened 2022-06-24 18:08 UTC by karakanb

Signed-off-by: Burak Karakan <burak.karakan@gmail.com>

## What issues does your PR fix?

- N/A

## What does your PR do?

This PR introduces a new value `dags.gitSync.submodules` (default: `recursive`) to control the submodule strategy for git-sync pods.

In my use case, the repo that is being cloned has a lot of submodules, but I would rather not init the submodules because it takes 20+ seconds, therefore I want to be able to disable the submodules to significantly speed up my tasks.

## Checklist

### For all Pull Requests

- [x] Commits are [signed off](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#sign-your-work)
- [x] Commits have [semantic messages](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#semantic-commit-messages)
- [ ] Documentation [updated](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#documentation)
- [x] Passes [ct linting](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#linting)

### For releasing ONLY

- [ ] Chart.yaml [version bumped](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#versioning)
- [ ] CHANGELOG.md updated

2022-06-26 16:47 UTC, karakanb commented
@thesuperzapper should I update the version with this as well? would you consider this as a minor version or a patch version?

2022-09-01 23:36 UTC, thesuperzapper commented
@karakanb thanks for the PR, don't worry, I haven't forgotten it!

As it adds value, it will need to be part of `8.7.0`, my main goal for `8.7.0` is to have the task-aware autoscaler (https://github.com/airflow-helm/charts/issues/339), which is taking an incredible amount of work to get done but is progressing!

If enough feature PRs build up before then, we might cut `8.7.0 early` which would probably include this PR.

2022-12-21 03:17 UTC, thesuperzapper commented
> @thesuperzapper hey Mathew, I hope you are doing well. Do you happen to have a release schedule in mind? it feels like smaller changes like these can go as part of patch versions as long as they are backwards compatible, and would avoid blocking other smaller features until the big ones you'd like to have are ready, as well as avoiding the need to fork by others.
> 
> Would you be interested in releasing some patch versions with fixes like this, as well as support for newer k8s versions for issues such as #679?

@karakanb sorry about the delay in getting this PR in a release, I have been busy moving countries!

So I can prioritize what to include, what are the critical fixes/features which you would expect in the next release?

2023-02-07 02:05 UTC, thesuperzapper requested changes
@karakanb thanks for the PR, there are only a few minor changes (see comments) that I think we need.

Also, we should update the ["Load Airflow DAGs" FAQ page](https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/dags/load-dag-definitions.md#option-1---git-sync-sidecar) to show the new `submodules` value in its examples.

2023-02-07 02:05 UTC, thesuperzapper commented on charts/airflow/values.yaml
> +    submoduleStrategy: recursive
I think we can just call the value `submodules`, for consistency with the [git-sync command-line and environment variable parameters](https://github.com/kubernetes/git-sync#manual).

2023-04-06 02:08 UTC, thesuperzapper approved these changes
@karakanb thanks for the PR, I will be releasing this today in version `8.7.0` of the chart.

2023-04-07 01:22 UTC, merged