feat(priorityClassName): Allow users to set priorityClassName
airflow-helm/charts pull request #648
Opened 2022-09-20 18:36 UTC by pkalemba

## What issues does your PR fix?

- fixes #XXX
- fixes #YYY

## What does your PR do?

Adds priorityClassName to pods

## Checklist

### For all Pull Requests

- [X] Commits are [signed off](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#sign-your-work)
- [X] Commits have [semantic messages](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#semantic-commit-messages)
- [X] Documentation [updated](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#documentation)
- [ ] Passes [ct linting](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#linting)

### For releasing ONLY

- [ ] Chart.yaml [version bumped](https://github.com/airflow-helm/charts/tree/main/charts/airflow/CONTRIBUTING.md#versioning)
- [ ] CHANGELOG.md updated

2022-09-28 17:39 UTC, pkalemba commented
@thesuperzapper can You look at it please?

2022-12-09 09:46 UTC, pkalemba commented
Can someone look at it ?

2023-02-07 02:22 UTC, thesuperzapper requested changes
@pkalemba you are amazing! Thanks for this PR!

I have left a small number of comments that need to be fixed, but otherwise it looks good for the next release.

2023-02-07 02:22 UTC, thesuperzapper commented on charts/airflow/values.yaml
> +  defaultPriorityClassName: ""
To keep things consistent let's use the same formatting as the other docstrings:

```yaml
  ## default priorityClassName for airflow Pods (is overridden by pod-specific values)
  ## - docs for priorityClassName:
  ##   https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/
  ##
  defaultPriorityClassName: ""
```

2023-02-07 02:22 UTC, thesuperzapper commented on charts/airflow/values.yaml
> +    priorityClassName: ""
Let's add a link for people who don't know what `priorityClassName` is:

```yaml
  ## the priorityClassName for the db-migrations Pods
  ## - docs for priorityClassName:
  ##   https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/
  ##
  priorityClassName: ""
```

__NOTE:__ we will also need to add it to all the other `priorityClassName` docstrings in this values file

2024-05-26 17:39 UTC, closed without merging